### ISSUE TITLE
components directories camelcase

### ISSUE THREAD

**Issue by Bruno17** [jaredfhealy/extrabuilder#10]
As far, as I've seen on other Extras, they have allways lowercase directory names in core/components and assets/components. I think it could lead to issues at some point having them camelcase.

**Comment by jaredfhealy** [comment]
This is one of the shifts with MODX 3 that I have seen. We no longer have any dependency on directory and file naming conventions because all the classes utilize namespaces. Take a look at MODX itself as an example:

`...core/src/Revolution/`

From that point down the directory structure all the folders are capitalized which wasn't done in the past. As you have seen, trying to figure out the "MODX 3" standard going forward seems to still be a work in progress with very little documentation or guidance.

My thought on this one was if we have no dependency on file structure because classes are autoloaded, why not match the component directory for the Extra to it's namespace? If there is a technical reason that would be good to know. But also if the core team had a "standard" they wanted to publish I'd also follow that.

![image](https://user-images.githubusercontent.com/9794500/149781989-ff958e85-c8b8-4fd3-b9e0-e1b5b31e6f1a.png)

**Comment by Bruno17** [comment]
hmm.... 
also GPM for-3 converts all to lowercase
https://github.com/theboxer/Git-Package-Management/blob/a89aad524befcfdd84b78bf8001360d7df24a6d3/core/components/gpm/src/Config/Parts/General.php#L46

**Comment by jaredfhealy** [comment]
Most of the examples I saw as well are using lowercase still like "tagger", but I think this is maybe more due to them trying to remain backward compatible? The namespace documentation I was reading and somewhere else that I can't quite find, mentioned that MODX will treat the namespaces like directories or that we will mirror the directory structure.

Example with MODX: composer.json specifies a psr-4 prefix as `MODX\\` being equivalent to `core/src/`

![image](https://user-images.githubusercontent.com/9794500/149789517-598049ba-b619-4309-b13d-3feec73359c3.png)

What I think this does, maybe only during the build?
Namespace: `MODX\Revolution\Processors\Security\Role`
That is translated to a directory: `core/src/Processors/Security/Role`

That is what I am trying to do here...

My namespace: `ExtraBuilder\Model\ebPackage`
Direcotry: `ExtraBuilder\src\Model\`

In the case of my Extra the "Namespace prefix" is passed in parse schema

![image](https://user-images.githubusercontent.com/9794500/149790924-2fb29635-6278-457f-be79-989b0f359e59.png)

**Comment by jaredfhealy** [comment]
Also worth mentioning, if you create your namespace as lowercase, and the paths are lowercase in the namespace entry, then ExtraBuilder will just mirror that and your directories will all be lowercase as well.

**Comment by Bruno17** [comment]
Sure, but....

The reason, I'm asking is:
Currently I'm creating my packages, schemas, class files, tables with help of the MIGX package manager on MODX 2. They actually are cross compatible this way. 
But in future, I will need a new way to create all the stuff with the new MODX 3 way.
So, I was looking into your ExtraBuilder, if it eventually could replace my MIGX package manager for MODX 3.
But the created structure has to be GPM compatible for me.
If it isn't, I have to rebuild my package manager for MODX 3.

**Comment by jaredfhealy** [comment]
I'll definitely take a look and see how I could make it compatible. Or perhaps there is an option added to build for GPM or similar.

**Comment by jaredfhealy** [comment]
This is now resolved and follows the standard directory capitalization and structure.
